/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MysqlConnection;
import Controller.PraticienController;
import Model.Praticien;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ENODO02
 */
public class PraticienEdit extends javax.swing.JFrame {

    /**
     * Creates new form PraticienModif
     */
    public PraticienEdit() {
        initComponents();
        
        Show_Combo_Praticien();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabModifP = new javax.swing.JLabel();
        LabNom = new javax.swing.JLabel();
        p_nom = new javax.swing.JTextField();
        EnregistrerBTN = new javax.swing.JButton();
        LabPrenom = new javax.swing.JLabel();
        p_prenom = new javax.swing.JTextField();
        LabAdresse = new javax.swing.JLabel();
        p_adresse = new javax.swing.JTextField();
        LabVille = new javax.swing.JLabel();
        p_ville = new javax.swing.JTextField();
        LabTel = new javax.swing.JLabel();
        p_telephone = new javax.swing.JTextField();
        LabCp = new javax.swing.JLabel();
        p_codepostal = new javax.swing.JTextField();
        LabSecteur = new javax.swing.JLabel();
        p_secteur = new javax.swing.JTextField();
        SupprimerBTN = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        LabNom1 = new javax.swing.JLabel();

        LabModifP.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        LabModifP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/utilisateur_plus_v.png"))); // NOI18N
        LabModifP.setText("  Modifier un Praticien");

        LabNom.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabNom.setText("Nom :");

        p_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_nomActionPerformed(evt);
            }
        });

        EnregistrerBTN.setBackground(new java.awt.Color(153, 255, 153));
        EnregistrerBTN.setText("Modifier un praticien");
        EnregistrerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerBTNActionPerformed(evt);
            }
        });

        LabPrenom.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabPrenom.setText("Prénom :");

        LabAdresse.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabAdresse.setText("Adresse :");

        p_adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_adresseActionPerformed(evt);
            }
        });

        LabVille.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabVille.setText("Ville:");

        LabTel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabTel.setText("Téléphone :");

        p_telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_telephoneActionPerformed(evt);
            }
        });

        LabCp.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabCp.setText("Code Postal :");

        LabSecteur.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabSecteur.setText("Secteur :");

        SupprimerBTN.setBackground(new java.awt.Color(255, 102, 102));
        SupprimerBTN.setText("Supprimer le praticien");
        SupprimerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerBTNActionPerformed(evt);
            }
        });

        jComboBox1.setSelectedItem(jComboBox1);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        LabNom1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabNom1.setText("Sélectionner le praticien :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(EnregistrerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(SupprimerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabNom, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabAdresse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabVille, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(p_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(p_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p_ville, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabTel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(LabCp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabSecteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_codepostal, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(p_telephone)
                    .addComponent(p_secteur, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabModifP, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabModifP)
                    .addComponent(LabNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabNom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabCp)
                    .addComponent(p_codepostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabPrenom)
                    .addComponent(LabTel)
                    .addComponent(p_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabAdresse)
                    .addComponent(p_secteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabSecteur))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabVille))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnregistrerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupprimerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_nomActionPerformed

    private void EnregistrerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerBTNActionPerformed
        String NomPrenom = jComboBox1.getSelectedItem().toString();
        
        String nom = p_nom.getText();
        String prenom = p_prenom.getText();
        String adresse = p_adresse.getText();
        String ville = p_ville.getText();
        String code_postal = p_codepostal.getText();
        String telephone = p_telephone.getText();
        String secteur = p_secteur.getText();
        
        PraticienController monPraticien = new PraticienController();
        monPraticien.EditPraticien(NomPrenom,nom, prenom, adresse, ville, code_postal, telephone, secteur);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_EnregistrerBTNActionPerformed

    private void p_adresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_adresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_adresseActionPerformed

    private void p_telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_telephoneActionPerformed

    private void SupprimerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerBTNActionPerformed
        String praticienSelect = jComboBox1.getSelectedItem().toString();
        PraticienController monPraticien = new PraticienController();
       
        monPraticien.DeletePraticien(praticienSelect);
        this.setVisible(false);
        
    }//GEN-LAST:event_SupprimerBTNActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        /*
        sélection de l'utilisateur via le nom-prenom du visiteur
        */
        String praticienSelect = jComboBox1.getSelectedItem().toString();
        
        
        PraticienController monPraticien = new PraticienController();
        Praticien monSelectPraticien = new Praticien();
         
        monSelectPraticien = monPraticien.selectPraticienByNom(praticienSelect);   
            
            p_nom.setText(monSelectPraticien.getNom());
            p_prenom.setText(monSelectPraticien.getPrenom());
            p_adresse.setText(monSelectPraticien.getAdresse());
            p_ville.setText(monSelectPraticien.getVille());
            p_codepostal.setText(monSelectPraticien.getCode_postal());
            p_telephone.setText(monSelectPraticien.getTelephone());
            p_secteur.setText(monSelectPraticien.getSecteur());
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PraticienEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PraticienEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PraticienEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PraticienEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PraticienEdit().setVisible(true);
            }
        });
    }
    
     public void Show_Combo_Praticien()
    {
        try 
        { 
            Connection connection = MysqlConnection.ConnectDB();
            Statement st = connection.createStatement();
            String query = "SELECT * FROM praticien ";
            ResultSet rs = st.executeQuery(query);

            while(rs.next())
            {      
               String name = rs.getString("nom");
               jComboBox1.addItem(name);             
            } 
            connection.close();
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnregistrerBTN;
    private javax.swing.JLabel LabAdresse;
    private javax.swing.JLabel LabCp;
    private javax.swing.JLabel LabModifP;
    private javax.swing.JLabel LabNom;
    private javax.swing.JLabel LabNom1;
    private javax.swing.JLabel LabPrenom;
    private javax.swing.JLabel LabSecteur;
    private javax.swing.JLabel LabTel;
    private javax.swing.JLabel LabVille;
    private javax.swing.JButton SupprimerBTN;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField p_adresse;
    private javax.swing.JTextField p_codepostal;
    private javax.swing.JTextField p_nom;
    private javax.swing.JTextField p_prenom;
    private javax.swing.JTextField p_secteur;
    private javax.swing.JTextField p_telephone;
    private javax.swing.JTextField p_ville;
    // End of variables declaration//GEN-END:variables
}
