/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UtilisateurController;
import Controller.VisiteurController;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author passpass
 */
public class UtilisateurList extends javax.swing.JFrame {

    /**
     * Creates new form UtilisateurList
     */
    public UtilisateurList() {

        initComponents();

        UtilisateurController myUserC = new UtilisateurController();
        DefaultTableModel model = (DefaultTableModel) visiTable.getModel();

        myUserC.showUserListInJTable(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listeComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        visiTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        recherche = new javax.swing.JTextField();

        setLocation(new java.awt.Point(300, 300));

        listeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Login", "Email", "Nom", "Prénom", "Adresse", "Ville", "Secteur", "Laboratoire" }));
        listeComboBox.setEnabled(false);
        listeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listeComboBoxItemStateChanged(evt);
            }
        });

        visiTable.setForeground(new java.awt.Color(0, 0, 0));
        visiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login", "Email", "Role", "Nom", "Prénom", "Adresse", "Ville", "Secteur", "Laboratoire"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        visiTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(visiTable);
        visiTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (visiTable.getColumnModel().getColumnCount() > 0) {
            visiTable.getColumnModel().getColumn(7).setPreferredWidth(20);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Liste des Utilisateurs");

        recherche.setToolTipText("Rechercher dans la sélection ...");
        recherche.setEnabled(false);
        recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 271, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 322, Short.MAX_VALUE)
                        .add(listeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 262, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(recherche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 262, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(listeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(recherche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 362, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheActionPerformed

    private void listeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listeComboBoxItemStateChanged

        /*
        *   
        *   Affiche le tableau trié par le champs sélectionné du menu déroulant
        *
         */
        boolean isTableVisiteur;
        boolean isTableUtilisateur;
        String tableSelect;         // contient la sélection du champ sélectionné par le menu deroulant

        DefaultTableModel model = (DefaultTableModel) visiTable.getModel(); // model decrivant le contenu de la liste du tableau
        Object monNewRowUser = new Object();
        Object monNewRowVisiteur = new Object();
        UtilisateurController myUser;
        VisiteurController myVisiteur;
        myVisiteur = new VisiteurController();
        myUser = new UtilisateurController();

        tableSelect = listeComboBox.getSelectedItem().toString();

        isTableVisiteur = tableSelect.compareTo("Nom") == 0 || tableSelect.compareTo("Prénom") == 0 || tableSelect.compareTo("Adresse") == 0 || tableSelect.compareTo("Ville") == 0 || tableSelect.compareTo("Secteur") == 0 || tableSelect.compareTo("Laboratoire") == 0;
        isTableUtilisateur = tableSelect.compareTo("Login") == 0 || tableSelect.compareTo("Email") == 0 || tableSelect.compareTo("Rôle") == 0;

        /*
        *  La sélection se fait par un champ visiteur
         */
        if (isTableVisiteur) {
            if (tableSelect.compareTo("Nom") == 0) {
                tableSelect = "nom";
            }
            if (tableSelect.compareTo("Prénom") == 0) {
                tableSelect = "prenom";
            }
            if (tableSelect.compareTo("Adresse") == 0) {
                tableSelect = "adresse";
            }
            if (tableSelect.compareTo("Ville") == 0) {
                tableSelect = "ville";
            }
            if (tableSelect.compareTo("Secteur") == 0) {
                tableSelect = "secteur";
            }
            if (tableSelect.compareTo("Laboratoire") == 0) {
                tableSelect = "labo";
            }
            monNewRowVisiteur = myVisiteur.showVisiteurListInJTableByTable(model, tableSelect);
            //   String listV = "listV";
        } /*
        *   La sélection se fait par un champ utilisateur
         */ else if (isTableUtilisateur) {
            if (tableSelect.compareTo("Login") == 0) {
                tableSelect = "login";
            }
            if (tableSelect.compareTo("Email") == 0) {
                tableSelect = "email";
            }
            if (tableSelect.compareTo("Rôle") == 0) {
                tableSelect = "id_role";
            }

            monNewRowUser = myUser.showUserListInJTableByTable(model, tableSelect);
            //  String listU = "listU";

        } else {
            JOptionPane.showMessageDialog(null, "Erreur dans le choix de la colonne de tri !");
        }

    }//GEN-LAST:event_listeComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilisateurList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilisateurList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilisateurList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilisateurList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtilisateurList().setVisible(true);
            }
        });
    }

    /**
     * getter pour accéder au menu déroulant permettant de trier la liste
     *
     * @return
     */
    public JComboBox<String> getUserBox() {
        return listeComboBox;
    }

    /**
     * setter pour modifier le menu déroulant permettant de trier la liste
     *
     * @param UserBox
     */
    public void setUserBox(JComboBox<String> UserBox) {
        this.listeComboBox = UserBox;
    }

    /**
     * getter pour accéder au contenu saisi dans le champ Recherche
     *
     * @return
     */
    public JTextField getRecherche() {
        return recherche;
    }

    /**
     * setter pour modifier le contenu saisi dans le champ Recherche
     *
     * @param recherche
     */
    public void setRecherche(JTextField recherche) {
        this.recherche = recherche;
    }

    /**
     * getter pour accéder au champs de la liste ( tableau )
     *
     * @return
     */
    public JTable getVisiTable() {
        return visiTable;
    }

    /**
     * setter pour modifier les champs de la liste ( tableau )
     *
     * @param visiTable
     */
    public void setVisiTable(JTable visiTable) {
        this.visiTable = visiTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listeComboBox;
    private javax.swing.JTextField recherche;
    private javax.swing.JTable visiTable;
    // End of variables declaration//GEN-END:variables
}
